### ISSUE TITLE
ASP.NET Core logging

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/EntityFramework.Docs#1039]
This page links to [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x) but there are no instructions on how to configure EF Core logging there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83069f-39a8-e992-95f7-a8b41154b6f4
* Version Independent ID: 144fe168-080f-6557-e4b2-a18adb4b89ed
* Content: [Logging - EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging)
* Content Source: [entity-framework/core/miscellaneous/logging.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/logging.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@paulomorgado the first paragraph in this page is the shortest answer: 

> EF Core integrates automatically with the logging mechanisms of ASP.NET Core whenever AddDbContext or AddDbContextPool is used.

That means that we automatically wire up things so that the DbContext will use the ILoggerFactory dependency of the application. For example, if you create an ASP.NET Core application with ASP.NET Core Identity, the code that you get from the templates already configures EF Core to use the logging configured in ASP.NET Core. Let us know if there is anything specific we could add to make this clearer.

**Comment by thomaslevesque** [comment]
If you're creating the `DbContext` manually, just make sure to call `UseApplicationServiceProvider` on the options builder, so that it uses the same services as the rest of the application.
