### ISSUE TITLE
EF Core one to one relation config

### ISSUE THREAD

**Issue by CwjXFH** [aspnet/EntityFramework.Docs#1063]
Hi,
i have something wrong when i use ef core

`Microsoft.EntityFrameworkCore.SqlServer`  **version**:2.2.0-preview3-35497
`System.Configuration.ConfigurationManager` **version**:4.5.0
**framework version**:.netcoreapp2.0
**OS version**: windows 10

My model class is:
```c#
public class UserInfo
{
    public Guid Id { set; get; }
    public string Name { set; get; }
    public int Age { set; get; }
    public Guid IdentifyId { set; get; }

    public Identify Identify { set; get; }
}

public class Identify
{
    public Guid Id { set; get; }
    public string Number { set; get; }
    public UserInfo UserInfo { set; get; }
}
```

I config one to one relation like this:
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<UserInfo>().ToTable("UserInfo");
    modelBuilder.Entity<Identify>().ToTable("Identify");

    modelBuilder.Entity<UserInfo>()
        .HasOne<Identify>()
        .WithOne(i => i.UserInfo)
        .HasForeignKey<UserInfo>(u => u.IdentifyId);
}
```
and then,run the query:
```c#
using (var context = new WJChiContext())
{
    var userInfoList = context.UserInfos;
    if (userInfoList != null && userInfoList.Any())
    {
        foreach (var info in userInfoList)
        {
            WriteLine(info.Identify.Number);
        }
    }
}
```
and get exception:`Unhandled Exception: System.Data.SqlClient.SqlException: column name 'IdentifyId1' is invalid.`
I config foreign key is `IdentifyId`,but the query sql contained `IdentifyId1`:
`SELECT [u].[Id], [u].[Age], [u].[IdentifyId], [u].[IdentifyId1], [u].[Name], [u].[UAddress]
FROM [UserInfo] AS [u]`

When i change the config like this:
```c#
modelBuilder.Entity<Identify>()
    .HasOne<UserInfo>()
    .WithOne(u => u.Identify)
    .HasForeignKey<UserInfo>(u => u.IdentifyId);
```
one to one  does not to work,the program above `WriteLine(info.Identify.Number);` will throw `System.NullReferenceException`,because the ef not query the Identity.

I use google to find the cause,but don't find the answer.

**Comment by ajcvickers** [comment]
@CwjXFH The first exception is because the relationship is defined like this:
```C#
modelBuilder.Entity<UserInfo>()
        .HasOne<Identify>()
        .WithOne(i => i.UserInfo)
        .HasForeignKey<UserInfo>(u => u.IdentifyId);
```
The `HasOne` call is made with no parameters, which means that even if there is a reference to `Identify` on `UserInfo`, then it should not be used for this relationship. This means that the `UserInfo.Identify` reference must represent a different relationship, for which another FK is required. If you want it to instead be used for this relationship, then try:
```C#
modelBuilder.Entity<UserInfo>()
        .HasOne<Identify>(u => u.Identify)
        .WithOne(i => i.UserInfo)
        .HasForeignKey<UserInfo>(u => u.IdentifyId);
```
See [defining relationships](https://docs.microsoft.com/en-us/ef/core/modeling/relationships) for more info.

The second exception is because you need to tell EF to load the related entity when executing a query. See [loading related data](https://docs.microsoft.com/en-us/ef/core/querying/related-data) for more info.
