### ISSUE TITLE
MySQL Provider Pre-Release Status

### ISSUE THREAD

**Issue by mark-monteiro** [aspnet/EntityFramework.Docs#1143]
The MySql.Data.EntityFrameworkCore provider is listed here as being in pre-release, but I do not see that classification anywhere else. Is that label here out of date? Or are there limitations with the provider I should be aware of? Here is the compatibility documentation from the latest release of the provider:

https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html#connector-net-entityframework-core-limitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9338b2a-93b1-595a-2e8e-86119e6eecbd
* Version Independent ID: 9890ab79-bc72-6075-4294-5450e6693668
* Content: [Database Providers - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/)
* Content Source: [entity-framework/core/providers/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@mark-monteiro thanks for bringing that to our attention. We don't have much more information about limitations of the official MySql provider than in the link you mentioned. Although we known many customers are using the Pomelo provider, we know the Pomelo provider is running our test suites, and has proper async support (because the underlying ADO.NET provider has it). 

Anyway, given the kind of information contained in the providers list, it is really easy for it to become stale. I will think about how to address that. 

Also, the documentation link could also be updated to point to https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html directly rather then the Connector/NET root page.
