### ISSUE TITLE
Error while adding migration

### ISSUE THREAD

**Issue by FaridGN** [aspnet/EntityFramework.Docs#1238]
Hi,

I use ASP.Net core 2.1 to build my web app. I followed all steps of configuration in startup and program.cs. But when I add migration through NuGet package console, it gives the following error:

> An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: The method or operation is not implemented.

Note that I implemented IDesignTimeDbContextFactory interface which was my previous error that wanted me to add implementation. After this, the error I mentioned above started to annoy me.
Please, help me with this.

``` csharp
 public class Program
    {
        public static void Main(string[] args)
        {
                var host = CreateWebHostBuilder(args).Build();
                using (var scope = host.Services.CreateScope())
                {
                    var services = scope.ServiceProvider;

                   OfferDbContext offerDbContext = services.GetRequiredService<OfferDbContext>();
                   OfferDb.Seed(offerDbContext);
                }
        }

        private static object BuildWebHost(string[] args)
        {
            throw new NotImplementedException();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

 public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<OfferDbContext>
    {
        OfferDbContext IDesignTimeDbContextFactory<OfferDbContext>.CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<OfferDbContext>();
            optionsBuilder.UseSqlServer("Data Source=WIN-5MLVUUQOKTM\\SQLEXPRESS");

            return new OfferDbContext(optionsBuilder.Options);
        }
    }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d786fb-de7d-de13-7989-c29bfb990e4f
* Version Independent ID: 2f981058-e284-cb85-574c-a2cade3f2174
* Content: [What is new in EF Core 2.1 - EF Core](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.1)
* Content Source: [entity-framework/core/what-is-new/ef-core-2.1.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-2.1.md)
* Product: **entity-framework**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by divega** [comment]
@FaridGN I suspect that the exception you are seeing is coming from the line that throws NotImplementedException in the BuildWebHost method in your code. 

There has been a change between ASP.NET Core 2.0 and later version on the pattern used for Program.cs that impacts how EF Core tools create the DbContext for design-time work.

In 2.0 the pattern had Program.Main and Program.BuildWebHost, as shown in https://docs.microsoft.com/aspnet/core/migration/1x-to-2x#update-main-method-in-programcs. 

In later versions the pattern includes the Program.CreateWebHostBuilder method instead of Program.BuildWebHost. For example:

``` csharp
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;

namespace DocsIssue1238
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
```

You seem to have a mix of both patterns. I wonder if that is why you seeing issues. 

I would suggest that you start with a clean Program.cs (like the one above) and see if that works. It is still possible that you may need to implement `IDesignTimeDbContextFactory<T>`, but the exception message tends to recommend implementing `IDesignTimeDbContextFactory<T>` even if something much simpler could work.
