### ISSUE TITLE
Please clarify "inheritance hierarchy" limitation

### ISSUE THREAD

**Issue by sbsw** [aspnet/EntityFramework.Docs#1239]
This article states:

&gt; **Current shortcomings**
&gt; Inheritance hierarchies that include owned entity types are not supported

I interpreted this to mean that entities that are in an inheritance hierarchy cannot include owned entities.  But, according to [this GitHub discussion](https://github.com/aspnet/EntityFrameworkCore/issues/14451#issuecomment-455362225) the limitation means that the owned entities themselves cannot be part of an inheritance hierarchy.  Please clarify this detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02e6748-42e0-000a-4945-42cd05a0b875
* Version Independent ID: e3effbd0-07f2-423d-4032-1722e75adb37
* Content: [Owned Entity Types - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities)
* Content Source: [entity-framework/core/modeling/owned-entities.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/owned-entities.md)
* Product: **entity-framework**
* GitHub Login: @AndriySvyryd
* Microsoft Alias: **ansvyryd**

**Comment by Vog-admin** [comment]
Agreed.  A few sentences down it also says:

> In EF Core 2.0, navigations to owned entity types cannot be declared in derived entity types unless the owned entities are explicitly mapped to a separate table from the owner hierarchy. This limitation has been removed in EF Core 2.1

I'm unclear if owned entity types are supported in inheritance hierarchies.

**Comment by kentliu2007** [comment]
I've tested this in EFCore 2.2. 
In fact, if we make more clarifications in the DbContext.OnModelCreating, for the included/owned entity, then this "Inheritance hierarchies that include owned entity types" still working.
For example, we have parent class User, and child class Teacher, if we have class UserContactInfo which owned by User with clarification:
modelBuilder.Entity<User>().OwnsOne(typeof(UserContactInfo), "UserContactInfo");
then we don't need to do so much clarifications for this UserContactInfo entity, only need 
modelBuilder.Entity<UserContactInfo>(entity => { entity.ToTable("UserContactInfo");}); 
is enough.
But if the class UserContactInfo owned by Teacher class (not by User class), with clarification
modelBuilder.Entity<Teacher>().OwnsOne(typeof(UserContactInfo), "UserContactInfo");
(sure, we don't need the Entity<User>().OwnsOne(...UserContactInfo) statement now, since User no longer owned the UserContactInfo),
then we need to add one more statement into the clarification:
modelBuilder.Entity<UserContactInfo>(entity =>
            {
                entity.HasKey("UserID");
                entity.ToTable("UserContactInfo");
             });
In above way, no matter the parent class, or the child class, they all can own their entities, while the EFCore will fire the SQL with "[User] left join [UserContactInfo]" content.

**Comment by laguer71** [comment]
This works because the owned types are mapped to a different table? Have you tried seeding data to the inherited member? have you tried doing table splitting instead of a different table? I tried and did not work for me... would like to know if I'm doing something wrong

**Comment by AndriySvyryd** [comment]
@laguer71 Those scenarios are supported. If you are getting errors create and issue on https://github.com/aspnet/EntityFrameworkCore/issues with a small repro project, preferably targeting 3.0.0

**Comment by kentliu2007** [comment]
@laguser71 Agree with above comment.  Before creating issue on Github, you can also check for my blogs for more detail example.  It is about using table split & owned types together.  But sorry, they are in Chinese, but the source code and screen shots are all English.  So just scroll the source code & screen part is enough.  The URLs are: https://www.cnblogs.com/fatkent/p/10436274.html & https://www.cnblogs.com/fatkent/p/10436991.html
