### ISSUE TITLE
SQLite: Is there support for Full Text Search?

### ISSUE THREAD

**Issue by lnaie** [aspnet/EntityFramework.Docs#1279]
Is it possible to do FTS with this provider? Via virtual tables and query operators: https://sqlite.org/fts5.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc4d900-28a8-9c04-2443-7407f15a684f
* Version Independent ID: 545bb0b5-f15b-584e-cef7-7283a0e0729f
* Content: [SQLite Database Provider - Limitations - EF Core](https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations)
* Content Source: [entity-framework/core/providers/sqlite/limitations.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/providers/sqlite/limitations.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by tgckpg** [comment]
Yes. It's essentially the same as creating a general table but you have to customize the migration queries.

Here are some example codes from one of my project:
* [DbContext](https://github.com/tgckpg/GR/blob/master/Database/Contexts/FTSData.cs)
* [Migration](https://github.com/tgckpg/GR/blob/master/Migrations/FTSData/20180223054441_Initial.cs)
* [Search](https://github.com/tgckpg/wenku10/blob/unsigned-master/wenku10/GR/DataSources/FTSDisplayData.cs#L73)

**Comment by lnaie** [comment]
Ok, I've looked into it and Microsoft.EntityFrameworkCore.Sqlite is built on top of SQLitePCLRaw.bundle_green (>= 1.1.12) which does not seem to have FTS5 feature implemented.
How does that work then?

**Comment by tgckpg** [comment]
I am not sure about the internal workings but I think the FTS5 extension is builtin to the SQLite library long ago. So as long as raw SQL is allowed then whatever the library provides is supported through the library.

[Section 2.1](https://www.sqlite.org/fts5.html)
> As of version 3.9.0 (2015-10-14), FTS5 is included as part of the SQLite amalgamation.

The basic idea is to create a `VIRTUAL TABLE` through raw SQL and querying it like a normal table ( with a twist ).

Since the search query for FTS is a bit different than that EFCore generates. You just need to also override it with `IQueryable.FromSql`. That's why you see `FTSData.cs` has a `Search` method.

The reason I notice this is I played with the SQLite CLI ( using it to read the db file that EFCore has generated ) and comparing the EFCore's raw SQL and don't really see the difference ( I can run `PRAMA whatever` from it which is neat! ).

**Comment by bricelam** [comment]
See https://github.com/aspnet/EntityFrameworkCore/issues/4823#issuecomment-381275855 for how to query in EF Core.

> SQLitePCLRaw.bundle_green (>= 1.1.12) which does not seem to have FTS5

bundle_green uses the system version of SQLite on macOS and iOS. To get a version that has FTS5 on those platforms, use bundle_e_sqlite3 instead: (in your csproj)

``` xml
<ItemGroup>
  <!--<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.2"/>-->
  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="2.2.2"/>
  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.12"/>
</ItemGroup>
```

**Comment by lnaie** [comment]
thanks everyone, very helpful.
