### ISSUE TITLE
Roll back the ASP.NET Core rename in the docs until new bits with the new name have shipped

### ISSUE THREAD

**Issue by danroth27** [aspnet/EntityFramework.Docs#131]
The link on http://docs.asp.net to the ASP.NET 5 + EF7 getting started topic broke, because the URL change to reflect the new ASP.NET Core rename. The rename should not be rolled out until after new bits with the new name have shipped.

**Comment by rowanmiller** [comment]
@natemcmaster could you roll this one back

**Comment by rowanmiller** [comment]
@danroth27 looking at this more, the link will still be broken anyway as we reorganized pages a little (the asp.net page is under `platforms` rather than `getting-started`). I'm going to roll back the title changes etc. to be "ASP.NET 5" until we launch... but given we need to change the link on ASP.NET site anyway, I think it makes sense just to leave the folder structure as-is since we'll just need to change it again when we release.

Here is the change to update the link https://github.com/aspnet/Docs/pull/976

**Comment by danroth27** [comment]
OK
