### ISSUE TITLE
Clarify that it is foreign key _constraint names_ (not FKs themselves) which cannot be configured with Data Annotations

### ISSUE THREAD

**Issue by vikriu** [aspnet/EntityFramework.Docs#1315]
Is it still relevant that Foreign keys  can't be created using Data Annotations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c8f247-1832-aac8-b783-7b9ba3337110
* Version Independent ID: 5120ef68-7b31-cdce-372d-4aa3ef497be2
* Content: [Foreign Key Constraints - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/relational/fk-constraints#feedback)
* Content Source: [entity-framework/core/modeling/relational/fk-constraints.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/relational/fk-constraints.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by DanielThyselius** [comment]
I don't think so, this seems to work:
[ForeignKey("Blog")]
public int PostId { get; set; }

**Comment by Perustaja** [comment]
Doesn't seem to work for me with regards to using data annotations as Daniel did.

using Microsoft.EntityFrameworkCore & System.ComponentModel.DataAnnotations after performing a successful dotnet add package Microsoft.EntityFrameworkCore.Relational still throws an error for 'ForeignKey' and 'ForeignKeyAttribute' not being found. Thought, I am really just trying to throw stuff together because the documentation, it seems, is right here and says you can't.
