### ISSUE TITLE
ef migrations add missing files

### ISSUE THREAD

**Issue by nikolaschou** [aspnet/EntityFramework.Docs#139]
I'm not sure if the following is a bug or a feature. But I wasted many hours being confused over this behavior. 

When I run "ef migrations add xxx" the migrations files are generated in the bin/output folder if existing migration files are found here. 

This is the output I see:
```
Finding DbContext classes...
Using context 'ApplicationDbContext'.
An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
Reusing directory of file '00000000000000_CreateIdentitySchema.cs'.
Reusing directory of file 'ApplicationDbContextModelSnapshot.cs'.
Writing migration to 'c:\Users\Nikola\Dev\SdmWeb\src\SdmWeb\bin\output\approot\src\SdmWeb\Migrations\20160223195618_v1.cs'.
Writing model snapshot to 'c:\Users\Nikola\Dev\SdmWeb\src\SdmWeb\bin\output\approot\src\SdmWeb\Migrations\ApplicationDbContextModelSnapshot.cs'.
Done. To undo this action, use 'ef migrations remove'
```

After cleaning the bin-folder the migration files are saved to the correct folder: c:\Users\Nikola\Dev\SdmWeb\src\SdmWeb\Migrations

I should emphasize that without the verbose-flag it is very easy to get confused by the migration files being produced in the bin/output folder.

In my opinion it should never produce the migration files in the bin/output folder but always directly in the Migration folder under the project root.

**Comment by smitpatel** [comment]
If there are existing migrations, then next migration would be placed in the same folder. This allows users to put migration files where they want. Since once user changes the folder where the files are stored next migration will be generated in that folder so user doesn't have to move files again. If there are no migrations files then it is put under Migrations folder under the project root.
There isn't anything specific to bin/output folder. Existing migration files shouldn't be in that folder.

**Comment by nikolaschou** [comment]
As I understand the migration files were copied to the bin/output folder because I ran dnu publish. I find this rather odd. But if this is really how it is designed to be, I can live with it and work around it.

**Comment by smitpatel** [comment]
That is interesting case. If migrations files are copied by dnu publish then there should be 2 folders containing exactly same migration files.
@bricelam - Where are the migration files are put if there multiple folders with previous migrations?

**Comment by bricelam** [comment]
>  The migration files were copied to the bin/output folder because I ran dnu publish. I find this rather odd.

I too find this odd. We should understand why it's doing this.

The algorithm is pretty straightforward: Find the first (if any) file named `<previous-migration-id>.cs` under the project directory and put the new migration next to it.

I don't think this will be a problem on the .NET Core CLI, since publish should only copy binaries and not sources in that world.

**Comment by bricelam** [comment]
P.S. @nikolaschou This is the documentation reop. Issues with the product should be filed against [aspnet/EntityFramework](https://github.com/aspnet/EntityFramework)

**Comment by rowanmiller** [comment]
> I don't think this will be a problem on the .NET Core CLI, since publish should only copy binaries and not sources in that world.

Agreed

**Comment by natemcmaster** [comment]
We added documentation for .NET Core CLI commands in #159. `dotnet publish` doesn't publish sources, so this isn't an issue anymore. As mentioned, product bugs should be filed to https://github.com/aspnet/EntityFramework
