### ISSUE TITLE
Entity Framework core exampes

### ISSUE THREAD

**Issue by Diaskhan** [aspnet/EntityFramework.Docs#1403]
Coul U add this demo examples of Ef core to Repo ?
https://github.com/andreluizsecco/EFCore.Demo
It very ussable !

![image](https://user-images.githubusercontent.com/15046677/55325035-af5dae00-54a5-11e9-9d2d-23e31f4c9a42.png)

```

```

### Steps to reproduce
```c#
```

**Comment by divega** [comment]
Thanks @Diaskhan for the pointer and the suggestion.

Members of our team that regularly present at conferences have been evolving a similar set of projects. You can always find the latest version using the https://aka.ms/efcoredemos shortcut.  

We have discussed moving the demos to either our documentation repo or our product repo. The truth is that it hasn't been a high priority to do so.  

Assuming @andreluizsecco could be interested in contributing, we are open to consider improving our demo projects. Otherwise we could consider linking to his from our documentation.

Currently we don't have a section for pointers to additional learning resources in our documentation, but we can consider adding it.

**Comment by andreluizsecco** [comment]
Thanks for the feedback @Diaskhan, I'm very happy to know that my demos are useful to you.

@divega I think amazing contribute with demos. I believe that the ideal would be to have a repository of the Entity Framework Core destined for demo projects, this would facilitate the search. If it's not possible now, feel free to link my repository to the documentation. If you need anything, I'm here to help.

**Comment by Diaskhan** [comment]
So what ideas about this issue ?
We close tham, or someone present PR ?

**Comment by Diaskhan** [comment]
Maybe To improve Docs Exmaple Must be Some Guide to  apply PR to this repository ?
I dont like A docs, beacause there is not example in docs!

Maybe its possible to apply commit if EF CORE REPO
That guides to this link  https://aka.ms/efcoredemos  ??

![image](https://user-images.githubusercontent.com/15046677/56456146-03173500-638a-11e9-9b1c-51001a79b977.png)

**Comment by andreluizsecco** [comment]
@diaskhan, the @divega had commented on the possibility of creating a repository just for these examples, but I have not seen any movement in that direction yet and I think if that happens it will be a long time. In this moment I think you could follow the repositories individually. Soon I will make more demos referring to version 3.0 in my repository. Let's wait and hope for the creation of this centralized repository of the product that contains the demos.

**Comment by divega** [comment]
> there is not example in doc

The are plenty of code samples in this repo, under https://github.com/aspnet/EntityFramework.Docs/tree/master/samples/core. In fact, many of the code snippets shown in documentation pages are from code maintained in those samples. 

> Maybe its possible to apply commit if EF CORE REPO that guides to this link https://aka.ms/efcoredemos ??

Not sure if you mean adding a link from the documentation pages or from the readme of the product repos. Both are possible. For the first one, we only need to figure out exactly where this belongs. As I mentioned before: 

> Currently we don't have a section for pointers to additional learning resources in our documentation, but we can consider adding it.

Do you have any suggestions? 

> I have not seen any movement in that direction yet and I think if that happens it will be a long time

Yes, juggling several other thigns at the moment, but if you have sugestions of where things go, or PRs for https://aka.ms/efcoredemos, that may help us make some progress.

**Comment by andreluizsecco** [comment]
So I think the best way to standardize this would be to create an official EF Core repository for demos, make a PR for a repository that is unofficial, honestly I do not see much sense. I believe it is not something that requires a lot of time and I consider something important (since one of the big problems that haunt the use of EF Core is the lack of good examples, wrong mappings, badly written queries, etc.), since it can direct who are beginning to use the features in the right way.

**Comment by Diaskhan** [comment]
The ef core has huge codebase ! 
Maybe is right to make repos for demos and apply commits from everbody! The problem when i try to make something unsually u must gogled! Some question could be closed via stackowerflow, some not ! For example i need customize imodelcustmozer and imodelcachekeyfactory, but it took many time to understand it ! With examples it be more easier i guesse !
