### ISSUE TITLE
Document SQLite client evaluation of decimals as a specific breaking change

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#1432]
See https://github.com/aspnet/EntityFrameworkCore/issues/15324

**Comment by bricelam** [comment]
Might also be worth mentioning DateTimeOffset, TimeSpan, and `ulong` too.

**Comment by bricelam** [comment]
The operations we should block server-eval for:

Expression | DateTime | DateTimeOffset | decimal | TimeSpan | ulong
--- | --- | --- | --- | --- | ---
-x | | | ❌ | ❌ | ✔
x + y | ❌ | ❌ | ❌ | ❌ | ✔
x / y | | | ❌ | ❌ | ❌
x > y | ✔ | ❌ | ❌ | ❌ | ❌
x >= y | ✔ | ❌ | ❌ | ❌ | ❌
x < y | ✔ | ❌ | ❌ | ❌ | ❌
x <= y | ✔ | ❌ | ❌ | ❌ | ❌
x % y | | | ❌ | | ❌
x * y | | | ❌ | ❌ | ❌
x - y | ❌ | ❌ | ❌ | ❌ | ✔
xs.Average() | | | ❌ | | 
xs.Max() | | ❌ | ❌ | ❌ | ❌
xs.Min() | | ❌ | ❌ | ❌ | ❌
xs.OrderBy() | ✔ | ❌ | ❌ | ❌ | ❌
xs.Sum() | | | ❌ | | ✔

Note, We can make TimeSpan work by registering two UDFs. See https://github.com/bricelam/EFCore.SqliteEx/issues/1

**Comment by ajcvickers** [comment]
@bricelam What does a tick represent as opposed to an x?

Also, would it, theoretically, be possible to make all of these work (or at least all that are non-lossy) by registering functions that understood the mapping and did conversion back to the appropriate .NET type? If so, should we consider doing this automatically at least when using EF Core?

**Comment by bricelam** [comment]
✔ - Works in SQL
❌ - Doesn't work
(blank) - No such operation

Yes, in theory, we could register UDFs for every operation and translate to them. But this is different from TimeSpan where we only need two UDFs to enable every operation.

> Should we consider doing this automatically at least when using EF Core?

I don't like the idea of doing it automatically since our UDF names may collide with the application's. The TimeSpan issue mentions making it an opt-in part of the provider via `optionsBuilder.UseSqlite(connection, x => x.UseTimeSpan())`

**Comment by ajcvickers** [comment]
Opt-in seems a good approach.

**Comment by bricelam** [comment]
Added to docs here: https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations#query-limitations
All invalid operations on these types are blocked in v3.
TimeSpan work tracked here: bricelam/EFCore.SqliteEx#1
