### ISSUE TITLE
Link to learning module about EF Core from EF Core docs

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1439]
We need to figure out the right place for it. 

https://docs.microsoft.com/learn/modules/persist-data-ef-core/ 

cc @CamSoper @scottaddie

**Comment by scottaddie** [comment]
@divega We link to it in the ASP.NET Core docs like this:

![image](https://user-images.githubusercontent.com/10702007/56505893-7b910980-64e2-11e9-80de-fd09f61f099d.png)

The MS Learn team doesn't provide guidance on how to link to the tutorials. I suggest adding a **Tutorials (Microsoft Learn)** ToC node. The link within should be more descriptive than **Data access** because the reader is in the EF Core docs already. Thoughts?

**Comment by divega** [comment]
@scottaddie are you planning to add more like this centers on EF Core? If yes, we can add a node for them. Otherwise I would like to add it to the existing Get Started menu.

**Comment by scottaddie** [comment]
@divega @CamSoper and I have plans to produce more advanced EF Core modules; however, those aren't likely to get done until late 2019 or early 2020. The focus right now is on finishing a basic beginner-to-intermediate level ASP.NET Core learning path.
