### ISSUE TITLE
Update suspendable execution strategy workaround to use AsyncLocal<bool>

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#1691]
This came up in blog post comments at https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-9-and-entity-framework-6-3-preview-9/#comments-2969. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b00663-cf69-4f4b-4d86-4b94c861e5ff
* Version Independent ID: 77d50147-5917-2af4-0aef-6c55dbaab6bd
* Content: [Connection resiliency and retry logic - EF6](https://docs.microsoft.com/en-us/ef/ef6/fundamentals/connection-resiliency/retry-logic#workaround-manually-call-execution-strategy)
* Content Source: [entity-framework/ef6/fundamentals/connection-resiliency/retry-logic.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/ef6/fundamentals/connection-resiliency/retry-logic.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@AndriySvyryd and @divega to decide on guidance here.

**Comment by divega** [comment]
@marchy, @AndriySvyryd and I were discussing early whether we should update the sample code for the suspendable execution strategy, or instead remove it.

The rationale for removing it is that using the second workaround listed of [calling the execution strategy manually](https://docs.microsoft.com/ef/ef6/fundamentals/connection-resiliency/retry-logic#workaround-manually-call-execution-strategy) should be more of a "pit of success" in most scenarios than using a suspendable execution strategy which you have high chances to *forget* resuming (un-suspending) if something goes wrong. 

I would like to know if you have considered the second strategy and if you have any thoughts on this.

**Comment by marchy** [comment]
Hi Diego, on further look into our adopted solution, we actually seem to indeed be using the manual retry strategy.

I don't recall the full set of issues we had around this (there were several, and we chased them for a while), but this is where it landed after the incorporating into DI as well as Repository / Unit of Work patterns etc:

```
public class EnhancedSqlAzureExecutionStrategy : SqlAzureExecutionStrategy {

	#region constants

	private static readonly IEnumerable<int> ErrorCodesToRetry = EnumHelper.Values<RetriableErrorCodes>().Select( _ => (int)_ );

	#endregion


	#region overrides

	protected override bool ShouldRetryOn( Exception exception ){
		switch( exception ){
		case SqlException sqlException:
			if( ErrorCodesToRetry.Contains( sqlException.Number ))
				return true;
			break;
		}
		return base.ShouldRetryOn( exception );
	}

	#endregion


	#region inner structures

	// REFERENCE: http://stackoverflow.com/questions/13159326/implementing-retry-logic-for-deadlock-exceptions
	private enum RetriableErrorCodes {
//			TimeoutExpired = -2,
//			Deadlock = 1205,
//			CouldNotOpenConnection  = 53,
//			TransportFail = 121,
		SnapshotIsolationUpdateConflict = 3960,
	}

	#endregion

}


public class EF6Helpers {

	#region operations

	public static void PerformUsingSupportForRetriableTransaction( Action operation ){
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = true;
		new EnhancedSqlAzureExecutionStrategy().Execute( operation );
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = false;
	}
	public static Task PerformUsingSupportForRetriableTransaction( Func<Task> operation, CancellationToken cancellationToken = new CancellationToken() ){
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = true;
		Task task = new EnhancedSqlAzureExecutionStrategy().ExecuteAsync( operation, cancellationToken );
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = false;

		return task;
	}
	public static async Task PerformUsingSupportForRetriableTransactionAsync( Func<Task> operation, CancellationToken cancellationToken = new CancellationToken() ){
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = true;
		await new EnhancedSqlAzureExecutionStrategy().ExecuteAsync( operation, cancellationToken );
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = false;
	}
	public static async Task<TResult> PerformUsingSupportForRetriableTransactionAsync<TResult>( Func<Task<TResult>> operation, CancellationToken cancellationToken = new CancellationToken() ){
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = true;
		TResult result = await new EnhancedSqlAzureExecutionStrategy().ExecuteAsync( operation, cancellationToken );
		EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = false;

		return result;
	}

	#endregion

}
```

USAGE:
```
await EF6Helpers.PerformUsingSupportForRetriableTransactionAsync( async () => {
	using( DbContextTransaction transaction = UnitOfWork.BeginTransaction() ){
		// fetch account
		Account account = await UnitOfWork.AccountRepository.Query()...

		...

	}
});
```

It would have been super for these helpers/patterns so have just come out of the box, since the default experience running on Azure definitely produced random failures that were hard to chase down.

**Comment by AndriySvyryd** [comment]
@marchy With 6.2+ You don't need to set `EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy` in `EF6Helpers`, it will ve suspended automatically when `EnhancedSqlAzureExecutionStrategy` is executing

**Comment by marchy** [comment]
@AndriySvyryd where is this implemented exactly?

The **SqlAzureExecutionStrategy** class seems to only check error codes in `ShouldRetryOn(..)`
```
public class SqlAzureExecutionStrategy : DbExecutionStrategy
  {
    /// <summary>
    /// Creates a new instance of <see cref="T:System.Data.Entity.SqlServer.SqlAzureExecutionStrategy" />.
    /// </summary>
    /// <remarks>
    /// The default retry limit is 5, which means that the total amount of time spent between retries is 26 seconds plus the random factor.
    /// </remarks>
    public SqlAzureExecutionStrategy()
    {
    }

    /// <summary>
    /// Creates a new instance of <see cref="T:System.Data.Entity.SqlServer.SqlAzureExecutionStrategy" /> with the specified limits for
    /// number of retries and the delay between retries.
    /// </summary>
    /// <param name="maxRetryCount"> The maximum number of retry attempts. </param>
    /// <param name="maxDelay"> The maximum delay in milliseconds between retries. </param>
    public SqlAzureExecutionStrategy(int maxRetryCount, TimeSpan maxDelay)
      : base(maxRetryCount, maxDelay)
    {
    }

    /// <inheritdoc />
    protected override bool ShouldRetryOn(Exception exception)
    {
      return SqlAzureRetriableExceptionDetector.ShouldRetryOn(exception);
    }
  }
```

or is this implemented lower down in **DbExecutionStrategy**?
I do see two `DbExecutionStrategy.Suspended = true` calls in `DbExecutionStrategy::Execute(..)` and `DbExecutionStrategy::ProtectedExecuteAsync(..)`


If this is the case why does the '[Workaround: Manually Call Execution Strategy](https://docs.microsoft.com/en-ca/ef/ef6/fundamentals/connection-resiliency/retry-logic#workaround-manually-call-execution-strategy)' section in the docs even exist?

The code example in the docs uses `SqlAzureExecutionStrategy` and states "We still need to suspend the execution strategy - using the technique shown above - so that any contexts used inside the retryable code block do not attempt to retry."

**Comment by AndriySvyryd** [comment]
@marchy Yes,  DbExecutionStrategy handles it. We didn't update the docs when the change was made, sorry for the confusion.

**Comment by marchy** [comment]
Oh okay, that's a great improvement.

Does this mean the section entire 'User initiated transactions are not supported' section is invalid then? Diego's comment above seemed to indicate only the first 'Workaround: Suspend Execution Strategy' workaround was outdated, but from what you're saying it sounds like both are.

If this is the case, is setting up the SqlAzureExecutionStrategy the only thing that's necessary now? (or in our case the EnhancedSqlAzureExecutionStrategy since there's the error code that we need to retry on as well)

ie:

**SETUP:**
```
public class MyConfiguration : DbConfiguration
{
    public MyConfiguration()
    {
        SetExecutionStrategy(
            "System.Data.SqlClient",
            () => new EnhancedSqlAzureExecutionStrategy(1, TimeSpan.FromSeconds(30)));
    }
}
```

**USAGE:**
_NOTE: No `EF6Helpers.PerformUsingSupportForRetriableTransactionAsync` shim anymore_
```
using( DbContextTransaction transaction = UnitOfWork.BeginTransaction() ){
	// fetch account
	Account account = await UnitOfWork.AccountRepository.Query()...
	...
}
```


PS: Should the SnapshotIsolationUpdateConflict 3960 error code perhaps be added into the list of codes retried out of the box as well? Not sure if it was considered and left out on purpose or whether it would be a helpful improvement

**Comment by AndriySvyryd** [comment]
@marchy You would still need to wrap the transaction in an Execute call:
```C#
new EnhancedSqlAzureExecutionStrategy(1, TimeSpan.FromSeconds(30).Execute(() =>
{
    using(DbContextTransaction transaction = UnitOfWork.BeginTransaction() ){
	// fetch account
	Account account = await UnitOfWork.AccountRepository.Query()...
	...
    }
});
```

**Comment by AndriySvyryd** [comment]
@marchy We considered retrying on 3960, but this isn't always the right thing to do. Developers should first consider whether a different isolation level would be more appropriate or whether the operation should be modified in response to the error.

**Comment by marchy** [comment]
Makes sense about 3960, thanks for confirming.


One thing I'm still confused about, what's the point of setting the `SetExecutionStrategy(..)` in the DbConfiguration initialization then?
```
SetExecutionStrategy(
	"System.Data.SqlClient",
	getExecutionStrategy: () => new EnhancedSqlAzureExecutionStrategy(1, TimeSpan.FromSeconds(30)));
}
```
This provides a factory lambda with the exact execution strategy construction code you show above, with a centralized way to specify configuration (ie: max retires & max delay) the same way our EF6Helpers utility did.

Without the need for setting `EF6DatabaseContext.EF6DatabaseConfig.SuspendSqlAzureExecutionStrategy = true/false` explicitly before & after every Execute call there shouldn't be any difference between calling `.Execute(..)` and having the framework internally utilize the default strategy, right?

**Comment by AndriySvyryd** [comment]
@marchy The difference is that the transaction is created inside of the `Execute` call. When there are no explicit transactions then EF can handle it fine.

**Comment by marchy** [comment]
I see, got it! Thanks for the clarifications Andriy.

Will await the update to the docs before we make our final changes in case we've missed anything.
