### ISSUE TITLE
datePartArg help content lacks critical information

### ISSUE THREAD

**Issue by jaxidian** [aspnet/EntityFramework.Docs#1705]
There is no way to identify valid strings to pass as the datePartArg argument. Should it be "day", "days", "d", "DAY", "D", "DAYS", "Days", "D@Y$"? It's impossible to tell from the documentation. If this is not going to be available via an enum somewhere, then the docs should either list or link to valid values to pass to the function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdc64607-37c0-fa25-45b4-03de96aaa53e
* Version Independent ID: 64e9c77e-ecae-2c18-31bc-34852f0ad014
* Content: [SqlFunctions.DateAdd Method (System.Data.Entity.SqlServer)](https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.sqlserver.sqlfunctions.dateadd?view=entity-framework-6.2.0#feedback)
* Content Source: [EF/xml/System.Data.Entity.SqlServer/SqlFunctions.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/EF/xml/System.Data.Entity.SqlServer/SqlFunctions.xml)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@jaxidian - We do not intend to fix this. If you would like to update the documentation, we will consider a well-written community contribution. To update the documentation, PR needs to be created against the actual source code at https://github.com/aspnet/EntityFramework6

**Comment by shazam19** [comment]
This doesn't make sense. Why won't MS fix this? How the community supposed to write a documentation on this? Try out every possible alpha-numeric combination to check what works? This is ridiculous.

**Comment by ajcvickers** [comment]
@shazam19 We have limited resources to work on EF, which means we have to do some aggressive prioritization. Currently implementation and documentation for EF Core are much higher priority than making changes to the EF6 documentation. The chances of their being time for anything but critical doc changes for EF6 in the next few years is pretty low. Therefore, we prefer to be explicit about this and close the issue rather than leave it on the backlog with no chance of it actually getting worked on.

**Comment by shazam19** [comment]
That sounds like there's no future for EF. And everyone will be forced to move to EF Core.
