### ISSUE TITLE
If Database lost

### ISSUE THREAD

**Issue by SagorFox** [aspnet/EntityFramework.Docs#1743]
I have created database first project successfully but later, I have lost my existing database in the SQL Server and I want to use my application as before. How can I create a database same as before, should I delete models and scaffold again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 998197fe-077b-acee-c91c-12f074359e9e
* Version Independent ID: 7542e87e-8f99-9b91-6df1-6983776ad1d2
* Content: [Get started on ASP.NET Core - existing database - EF Core](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db#feedback)
* Content Source: [entity-framework/core/get-started/aspnetcore/existing-db.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/get-started/aspnetcore/existing-db.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by smitpatel** [comment]
@SagorFox - The data which was in database cannot be recovered by EF since we do not know about it. But for the schema part, you can scaffold a migration for your model and apply it to database and EF will create a database which matches your model. It would be nearly identical to database you had. More importantly, you can use it with EF like before.

**Comment by SagorFox** [comment]
I tried this, I don't need data! I only need the schema part! I tried for migration for times but it have showed "Build Failed". I will trying more times!

**Comment by SagorFox** [comment]
thank you!
