### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by domainmurat** [aspnet/EntityFramework.Docs#1772]
How to add include to index with fluent api or another way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f85ea32c-8d23-d61d-6036-cd772e3e95d9
* Version Independent ID: 25dd8ac4-2521-5200-0ddf-63ac8c83787a
* Content: [Indexes - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/indexes#feedback)
* Content Source: [entity-framework/core/modeling/indexes.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/indexes.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by roji** [comment]
I'm assuming you're asking how to include columns inside your index. If that's the case [see the documentation here](https://docs.microsoft.com/en-us/ef/core/modeling/relational/indexes#include-columns-in-sql-server-indexes), otherwise post back and I'll reopen the issue.

Note: I'll be merging the relational index doc page (where this info lives) into the general index modeling page, that's already tracked by #1669
