### ISSUE TITLE
EF 6.3 + MSSQL CE (Edmx) in dotnet core 3.0 without app.config

### ISSUE THREAD

**Issue by parad74** [aspnet/EntityFramework.Docs#1794]
In inssues 

`https://github.com/aspnet/EntityFramework6/issues/1316`

there is possibility to use EF 6.3 + MSSQL CE (Edmx) in dotnet core 3.0 without app.config

Developers who want to migrate their Application with data-level on MSSQL CE, most of them with MSSQL CE  ~10 year. And if the systems are migrating now so users need these Applications and they are in progress. To transfer a large system with a large number of users with a change in the data-level and model is unrealistic. If the level of the model is working, then the chances increase.

Make it possible to use workaround with EF 6.3 + MSSQL CE (Edmx) in dotnet core 3.0 without app.config. I think, there are steps that can be added to the package "EntityFramework.SqlServerCompact"

EF 6.3
MSSQL CE
Edmx
without app.config

**Comment by ajcvickers** [comment]
@parad74 It should be possible to use EF 6.3 with an EDMX and no app.config. If any of this isn't working then please file an issue at https://github.com/aspnet/EntityFramework6 including a small, runnable project/solution that demonstrates the problem.

We do not intend to continue supporting SQL CE on EF going forward. We aren't intentionally breaking anything, but we're not explicitly bringing it to .NET Core because the underlying technology is no longer being developed and will go out of support completely very soon.
