### ISSUE TITLE
Guidance on applying migrations during KUDU deploy

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#180]
We've had a few folks ask about this. It should be possible with CLI commands, but folks have reported errors trying to do so. We should get it working and then document how to do it.

**Comment by natemcmaster** [comment]
The follow is definitely I-know-what-I-am-doing territory. I'll let @rowanmiller figure out how to make this more palatable to users.

First of all, this is not specific to KUDU. This applies to anyone who wants to run migrations on a .NET Core app after `dotnet publish` and does not have source code available. To do this, we need to run an alternate entry point on our published app. Here are the magic incantations to make it possible to run "database update" on published output.

### Project setup

 **Before publish**

Make sure "Microsoft.EntityFrameworkCore.Design" is a regular dependency and is **not** `"type": "build"`

```json
"dependencies": {
   "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-*"
}
```

`"type": "build"` will prevent design time tooling (aka Microsoft.EntityFrameworkCore.Design) from ending up in output when `dotnet publish` is called. So use "Microsoft.EntityFrameworkCore.Design" as a regular dependency.

**On published output**
Execute an alternate entry point on your published output. Again, this is **published** output (dotnet-publish) not compiled output (dotnet-build). 
```
dotnet exec \
    --runtimeconfig MyWebApp.runtimeconfig.json \
    --depsfile MyWebApp.deps.json \
    Microsoft.EntityFrameworkCore.Design.dll \
    --assembly MyWebApp.dll \
    --verbose \
    database update
```

### What this is doing

To run .NET Core, you need a few things.

1. CoreCLR
2. The "host policy"
3. System.Runtime (it's like mscorlib, but for .NET Core)
4. All of your app's dependencies
5. An assembly with an ECMA entry point (Program.Main)

### Breaking down the incantation

Step | Explanation
------|-------
`dotnet exec` | An undocumented command. 
`--runtimeconfig MyWebApp.runtimeconfig.json` | Helps us requirements 1-3. The runtime config file contains info about which version of the shared framework we want. Additionally, specifieds any other runtime config options.
`--depsfile MyWebApp.deps.json` | Deps.json = "all of my app's dependencies". Requirement 4.
`Microsoft.EntityFrameworkCore.Design.dll` | Requirement 5. Our entry point.
`--assembly MyWebApp.dll --verbose database update` | The rest of this stuff flow through in to the "Program.Main" of Microsoft.EntityFrameworkCore.Design. Because we don't have a project system anymore, we need to explicitly tell the EF commands which assembly to use.

### One more tidbit

You will actually see `dotnet exec` in log output when you run `dotnet ef --verbose` on a project. dotnet-ef.dll figures out your project system and invokes "dotnet exec", but in a much more user-friendly way.

**Comment by rowanmiller** [comment]
@natemcmaster thanks, I'll turn this into a doc

**Comment by natemcmaster** [comment]
Update: with https://github.com/aspnet/EntityFramework/pull/6288, this has changed slightly. To make this work, users will need to manually pull ef.exe or ef.dll out of the .Tools.VisualStudio or .Tools.DotNet nupkg. The guidance above about how to use dotnet exec still applies. Run `ef.exe --help` to see usage description.

**Comment by rowanmiller** [comment]
Consolidating with #204

**Comment by lomholdt** [comment]
@natemcmaster Do you know of a way to automatically resolve the `ef.dll` and copy it on `dotnet publish`? I have been looking but haven't found a way to dynamically reference the path to the file.
