### ISSUE TITLE
Clarify Backing Fields configuration

### ISSUE THREAD

**Issue by Costo** [aspnet/EntityFramework.Docs#273]
This is an issue regarding this documentation:
https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/modeling/backing-field.rst

When using expression bodied properties, the backing field convention does not work. The field needs to be configured with `AddAnnotation("BackingField",  "_myField");`

**This works**

```
public class MyEntity
{
  private double _distance;
  public double Distance
  { 
    get { return _distance; }
    set { /* ignored */ }
  }
}
```

**This doesn't work**

```
private double _distance;
public double Distance => _distance;
```

Unless the model is configured with

```
protected override void OnModelCreating(ModelBuilder builder)
{
  ...
  builder.Entity<MyEntity>()
             .Property(x => x.Distance)
             .HasAnnotation("BackingField", "_distance");
}
```

**Comment by rowanmiller** [comment]
We only include properties with a getter and setter in the model by convention. The expression body property does not have a setter, which is why it is not included by default. In the current release version, this actually won't work in a lot of cases. Query will use the field when creating instances of the class, but the state manager will throw if it ever needs to set the property. For this reason, we don't consider readonly properties to be a supported feature in 1.0.

We do have proper backing field support coming in 1.1 (I'll update the docs with this when we release 1.1).
