### ISSUE TITLE
Please document supported CLR/LINQ functions for EF Core

### ISSUE THREAD

**Issue by denisz1** [aspnet/EntityFramework.Docs#348]
No one likes those "cannot be converted to a store expression" errors at runtime.

For regular EF, there is a very helpful [list of supported CLR methods](http://msdn.microsoft.com/en-us/library/bb738681(v=vs.110).aspx), and a [list of supported LINQ methods](http://msdn.microsoft.com/en-us/library/bb738550(v=vs.110).aspx).

I can't find something similar for Core in the [official documentation ](http://docs.microsoft.com/en-gb/ef/core/). (If those docs are still valid for Core, then just a link to them would be good enough.)

**Comment by ErikEJ** [comment]
As I understand it, all LINQ methods and CLR functions work with EF Core. The ones that cannot be translated to SQL will be run using LINQ to Objects.  You can disable client evaluation: https://docs.microsoft.com/en-us/ef/core/querying/client-eval

**Comment by denisz1** [comment]
@ErikEJ I was hoping for official documentation. I know for example that some grouping operations are not supported. So like you said, some can't be translated to SQL.

Which ones?

That's why we need docs. If *everything* was supported, then we wouldn't.

**Comment by rowanmiller** [comment]
The list is ever-changing in EF Core at the moment, and can also vary from provider-to-provider, so I don't think it is practical to document that at this stage.

As @ErikEJ mentioned, everything should work but not everything will be processed in the database, some will be done in-memory (which is very different from EF6, where you would just get an exception). If you get a hold of the log output from EF Core, it will let you know whenever something was translated in-memory, rather than the database, so you can evaluate whether that is ok for your application (https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging).

**Comment by denisz1** [comment]
@rowanmiller Ok, thanks.

Your advice about checking logs is what we do, but it's not a great approach in the long run.

Once EF Core is more mature/stable (though it feels that way already, great job!), I hope you will consider formally documenting this, like for regular EF in those links.

**Comment by rowanmiller** [comment]
Will do
