### ISSUE TITLE
Getting Started: OSX

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework.Docs#4]
101 walkthrough similar to https://msdn.com/data/jj193542

**Comment by natemcmaster** [comment]
Note that async query only works on Mono >4.2.0

**Comment by rhires** [comment]
For getting started on Mac OS X and EF7 - it would seem that a version of NuGet closer to 3.0 is needed, but I have been unable to find instruction on updating beyond 2.8.5. I need 3.0 (which I know is still in beta) so I can get the EntityFramework.Commands -Pre because I see this message when trying to install using nuget.exe on the command line in Mac OS X: 
sudo nuget install EntityFramework.Commands -Pre
Password:
Attempting to resolve dependency 'EntityFramework.Relational.Design (≥ 7.0.0-beta6-13735)'.
Attempting to resolve dependency 'Microsoft.AspNet.Razor (≥ 4.0.0-beta6-11684)'.
Attempting to resolve dependency 'System.Collections (≥ 4.0.10-beta-23109)'.
The 'System.Collections 4.0.10-beta-23109' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.60318.667'.

What I'm doing so far is attempting to follow the full .net instructions, but substituting the Mac OS X specific stuff, and using PostgreSQL as the db...

**Comment by bricelam** [comment]
@rhires Until it's released, you might be able to build it from [NuGet/NuGet3](https://github.com/NuGet/NuGet3). They do have a `build.sh` script.

**Comment by rhires** [comment]
@bricelam - Thank you. I'm very much learning my way around github and all the stack stuff required to get some movement. I wish I had a better place to put all this down than here...I was able to download Nuget3-3.0-rc2-486 under the "Releases" tab, but then I got a build failure (which I'm happy to send or post the stack trace in the proper place) when I performed the build.sh. All of this is on my Mac OS X box...

**Comment by natemcmaster** [comment]
Added for beta6 #21

**Comment by rowanmiller** [comment]
Published doc can be found at http://ef.readthedocs.org/en/latest/getting-started/osx.html

**Comment by rhires** [comment]
Awesome! I was able to install, and worked out a few small kinks (which I documented) and I'm running!

**Comment by rowanmiller** [comment]
@rhires if there is anything that should be added to the docs feel free to open an issue... or send a pull request :smile:
