### ISSUE TITLE
Ef core - Add Microsoft access to the list of supported databases

### ISSUE THREAD

**Issue by scottaddie** [aspnet/EntityFramework.Docs#472]
Moved from https://github.com/aspnet/Docs/issues/4217. Filed by @bubibubi.

Is it possible to add EF core provider for Microsoft access (as for other 3rd parties providers)?

**Comment by divega** [comment]
@bubibubi It depends on what you mean. 

If you mean that you have a Microsoft Access database and you want a provider to exist for it, then that is a feature request and the question doesn't belong in any of the docs repos. I personally don't know of any EF Core provider for Microsoft Access and I don't think we would prioritize building it because we don't see demand for it.

If you meant that you know about the existence of such provider and you are confident that it works, then your question has now landed on the right repository.  Feel free to send a PR to add it to the list or at least provide the information here on how to get it and how to learn more about it (the kind of information we have for other providers).

**Comment by bubibubi** [comment]
@divega I meant your second option.

The source code is in this repository
https://github.com/bubibubi/EntityFrameworkCore.Jet
and you can find it also on nuget as
EntityFrameworkCore.Jet.
It supports all the EF features (also codefirst from database) but it can't handle complex queries and some data types (Jet can't).
(about PR is better I don't write in English for an 'official' documentation).
