### ISSUE TITLE
Document nulls in indexes

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#610]
For example, see comment here: https://github.com/aspnet/EntityFrameworkCore/issues/6794#issuecomment-365636279, but also consider documenting what we do for nulls with unique indexes for various providers.

**Comment by Davilink** [comment]
Its would be nice to add a Warning message or an informative message to explain that in EF Core 1.0, the model builder will create a filtered indexes by default and the only way to suppress that is to create the index manually with a raw query. I lost too much time because i had no way to know that the model builder was operating like that. The only way i found it was to inspect the index key in SQL Server Management Studio.

In my case i let the model builder create the index key (with the unique) and launch a homemade migration script to change it after the migration was executed to Drop/create and insert a migration entry in the « dbo.__EFMigrationsHistory » table to be sure that only execute once. A least if someone go in the DataContext, they can see that we have en unique index on the entity.
