### ISSUE TITLE
Define inheritance hierarchy as stated in the limitations

### ISSUE THREAD

**Issue by markarnolditpro** [aspnet/EntityFramework.Docs#713]
`Filters can only be defined for the root Entity Type of an inheritance hierarchy` .  
Please define inheritance hierarchy and provide a simple example of the limitation.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c9bd3e-4b99-9acf-48d8-e47bc53eb54e
* Version Independent ID: 220e0a6c-d227-956a-d27a-7c88804f770c
* Content: [Global Query Filters - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/filters)
* Content Source: [entity-framework/core/querying/filters.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/filters.md)
* Service: **unspecified**
* Product: **entity-framework**
* GitHub Login: @anpete
* Microsoft Alias: **anpete**

**Comment by ajcvickers** [comment]
@markarnolditpro It just means mapped classes that use normal class inheritance:
```C#
public class Document
{
}
public class Blog : Document
{
}
```
If Document and Blog are mapped, then the filter can only be applied to Document, not to Blog.

**Comment by LucaGabi** [comment]
Is there a "Global Query Projector" ? to include or exclude some table fields ?
If I have a column for each culture of a localized field I would use such a global option to select the correct field according to current selected culture.

**Comment by Dondudu** [comment]
I have an EF Core set of models where each model inherits from a BaseEntity, which contains some shared global properties (Id, IsDeleted, etc). By default, this gets mapped to a SQL Server database as [Table per Concrete Type](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-3-table-per-concrete-type-tpc-and-choosing-strategy-guidelines) which is great.

However, when I add a query filter as per the example:
```
modelBuilder.Entity<BaseEntity>().HasQueryFilter(p => !p.IsDeleted);
```
on the next migration EF wants to drop all my tables and create a single table called BaseEntity which is the [Table Per Hierachy](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph) pattern.

Is this expected behaviour? Any way to avoid it?
