### ISSUE TITLE
Code example relevance

### ISSUE THREAD

**Issue by iflare** [aspnet/EntityFramework.Docs#749]
The last code example has nothing to do with cascade delete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0fb981-4dec-7ff7-817b-6606f620b875
* Version Independent ID: c7517e7d-f011-a24c-53da-913771913998
* Content: [Saving Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/saving/related-data)
* Content Source: [entity-framework/core/saving/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/saving/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by psijkof** [comment]
It does. If you would enable logging on the DbContext, you would see the delete statements. The great thing is, on a code level, we 'just' work with the object tree. The nitty gritty is handled by EF Core.

**Comment by ajcvickers** [comment]
@iflare It depends on the definition of cascade delete. In this case, the delete is happening as a cascading effect of setting the navigation of a required relationship to null, thereby severing the dependent from the principal. Issue https://github.com/aspnet/EntityFrameworkCore/issues/10066 covers being able to separate this from a cascade that happens due to deletion of the principal.

**Comment by iflare** [comment]
@psijkof @ajcvickers Thank you both. I understand the logic behind it now. The explanation in Cascade Delete section is easier to understand  – "A closely related concept also covered by EF Core delete behaviors is the automatic deletion of a child entity when it's relationship to a parent has been severed--this is commonly known as "deleting orphans".
