### ISSUE TITLE
what about async and lazy loading

### ISSUE THREAD

**Issue by yonexbat** [aspnet/EntityFramework.Docs#754]
@thetylerb lazy loading is triggered as soon as you access a relational property. But is it loaded in a async way or a synchronous way?  I used to have IList&lt;QuestionOption&gt; options = await _context.QuestionOptions.Where(option =&gt; option.Question.Id == questionEntity.Id).ToListAsync(); it is now IList&lt;QuestionOption&gt; options = questionEntity.options

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@yonexbat Lazy-loading is always synchronous when triggered through navigation property access because navigation properties cannot be defined as async. The lazy-loading infrastructure contains async methods that can be used to do something similar in an async way, but it would be up to the application to wire this up whatever API makes sense. See the `ILazyLoader` class for the async methods.
