### ISSUE TITLE
Eager Loading - Include Syntax - is it a guarantee or hint ?

### ISSUE THREAD

**Issue by joe-oli** [aspnet/EntityFramework.Docs#838]
It should be stated somewhere prominent near the Eager Loading section whether the .Include syntax is a guarantee that EF will load associated relationships, or is it merely a hint? 

I've noticed different behaviour at different times, sometimes the root entity had relationships (navigation properties) loaded, at other times not (count was 0 for associated entities). Under what circumstances it WILL load vs it MAY load.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@joe-oli It's always will, never a hint. However, note that, "If you change the query so that it no longer returns instances of the entity type that the query began with, then the include operators are ignored."

If you are seeing behavior that is different from this, then please create a runnable project/solution or complete code listing that demonstrates this behavior and file a new issue on https://github.com/aspnet/EntityFrameworkCore/issues
