### ISSUE TITLE
I have a problem:

### ISSUE THREAD

**Issue by dovidW** [aspnet/EntityFramework.Docs#845]
Cannot open database "MyDatabase" requested by the login. The login failed.  Login failed for user 'DESKTOP-XXX\admin'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b15cd4c-9cba-c0e2-7618-7d621a3c5936
* Version Independent ID: f4681bc6-57be-6e69-cad9-776ce64d93bd
* Content: [Quick Overview - EF Core](https://docs.microsoft.com/en-us/ef/core/)
* Content Source: [entity-framework/core/index.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/index.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by axdiamond** [comment]
The account you are running Sql server as doesn't have permissions to create a database in the location you selected. You could get around this by running the sql sever agent ( not management studio ) as an account that has permissions to write to that directory.

However, you probably don't want to put your DB in `C:\Users\`, so instead of the above Id recommend putting it under another folder on your system, such as `C:\Users\<your username>\databases` or `C:\Development\Databases`, etc.
