### ISSUE TITLE
Can we include a sample in API documentation for Find?

### ISSUE THREAD

**Issue by samaune** [aspnet/EntityFramework.Docs#855]
Writing too many line with meaning less, it should attach a sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 681bc5c0-cca6-1811-ec3b-93742747e838
* Version Independent ID: c439f4b8-4edd-6faa-56a7-0779d46c3d99
* Content: [DbContext.Find Method (Microsoft.EntityFrameworkCore)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.find?view=efcore-2.1)
* Content Source: [dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml](https://github.com/aspnet/EntityFramework.ApiDocs/blob/live/dotnet/xml/Microsoft.EntityFrameworkCore/DbContext.xml)
* GitHub Login: @dotnet-bot

**Comment by ajcvickers** [comment]
Moved to https://github.com/aspnet/EntityFrameworkCore/issues/12906

**Comment by antonioortizpola** [comment]
Voting to close this issue. I do not see the docs as

> too many line with meaning less

First, I am guessing that it should be "too many meaningless lines" or maybe "too many lines with no meaning", but correct me if I am wrong, I am not a native speaker so I could be misunderstanding something.

On the other hand i am not so sure that the problem is the docs, as I see it could be that you need to practice your English more.
I mean, the find function is really easy to follow, you put a Type as Entity an object as ID (maybe some objects if it is a complex PK) and then the method return the entity if finds it or null if not, in this case I do not see how an example could be more clear.

Something like

```
...
class Blog {
    int Id { get; set; }
    string Name { get; set; }
}
...
var id = 1;
var entity = context.Find(Blog, 1);
if(blog == null) {
    //entity not found
}
```

I do not see hoe this could be more clarifying than the actual explanation, even the text also clarifies the usage of the EF cache if the entity is present, something that is very hard to explain with a simple code fragment example.
