### ISSUE TITLE
Inserting explicit values into store generated keys (IDENTITY_INSERT)

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework.Docs#86]
See example code and discussion in https://github.com/aspnet/EntityFramework/issues/2803

**Comment by rowanmiller** [comment]
Writing docs on this at the moment. Once we release RC2 we will need to update to provide an example of saving an explicit value on UPDATE for a `ValueGeneratedOnAddOrUpdate` property. 

This isn't really feasible in RC1 because https://github.com/aspnet/EntityFramework/issues/1441 prevents you using triggers, which is the only remotely realistic scenario I can think of for a `ValueGeneratedOnAddOrUpdate` property that you would want to update to an explicit value. The only thing that really works with `ValueGeneratedOnAddOrUpdate` is rowversion.

**Comment by rowanmiller** [comment]
Fixed in 6bb7689c05ccd627931cd1469b6e53a74e2d1003
Page is at https://docs.efproject.net/en/latest/saving/explicit-values-generated-properties.html
