### ISSUE TITLE
Question: Why we use the private constructor to inject the ILazyloader? not public?

### ISSUE THREAD

**Issue by zxs731** [aspnet/EntityFramework.Docs#865]
Why we use the private constructor to inject the ILazyloader? not public?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Loading Related Data - EF Core](https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by ajcvickers** [comment]
@zxs731 Two reasons:
* To demonstrate that it can be private
* Because ILazyLoader is a persistence concern only needed for this particular implementation of lazy loading. It is not part of the business/domain model. Therefore, one way of hiding this from the normal use of the domain model is to make it private.

**Comment by ajcvickers** [comment]
@zxs731 That's a valid position, but lazy-loading _must_ modify the behavior of the entity in some way to work. EF Core also supports proxies, which impacts the entity's behavior in a different way that you may prefer. If neither are acceptable, then the only option is to not use lazy loading.
