### ISSUE TITLE
Make alternate keys topic more helpful

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.Docs#883]
Helpfulness rating is very low.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2799173-ee3e-5650-14a8-b9185d45f730
* Version Independent ID: 36181ef7-bcb6-62a8-653d-3b89c8a11dd8
* Content: [Alternate Keys - EF Core](https://docs.microsoft.com/en-us/ef/core/modeling/alternate-keys)
* Content Source: [entity-framework/core/modeling/alternate-keys.md](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/modeling/alternate-keys.md)
* Product: **entity-framework**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by tdykstra** [comment]
Closing this issue: on 10/10/18 SkyRay showed 2k page views and 3 ratings (2 of them positive) for the last 30 days. The number of ratings is not enough to draw reliable conclusions; when we do the next sweep for high-traffic/low ratings docs, we can reopen this one if this doc meets those criteria.

**Comment by StingyJack** [comment]
@tdykstra - as is, its not terribly helpful, but that may be due to product limitations.  I came here looking for how to decorate properties as being natural keys when a surrogate was in use.  Perhaps that's just an area that EF doesn't serve. Its absence on the alternate key page isn't really telling me it does or does not.
