### ISSUE TITLE
Document explicitly that DbContext is not thread-safe

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework.Docs#922]

**Comment by mjrousos** [comment]
I can add something for this. 

I'm imagining a short new article containing:
1. An explanation that DbContext isn't thread-safe and shouldn't be used by multiple threads in parallel.
1. A couple example patterns of how to use EF safely in multi-threaded scenarios. This would essentially be different ways of getting separate DbContexts for each thread (create DbContext (perhaps from shared DbContextOptions) instead of retrieving from dependency injection, register DbContext as transient in DI, etc.).

Would that make sense for this one?
