### ISSUE TITLE
Example: To enable reverse engineering from an existing database does not work

### ISSUE THREAD

**Issue by aday12345** [aspnet/EntityFramework.Docs#99]
https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/getting-started/full-dotnet/existing-db.rst

The example to enable reverse engineering from an existing database does not work:
Scaffold-DbContext -provider EntityFramework.MicrosoftSqlServer -connection "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;"

when I tried this is vs2015 I get

The term 'Scaffold-DbContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:19
+ Scaffold-DbContext <<<<  -provider EntityFramework.MicrosoftSqlServer -connection "Server=sqldev\sqltest;Database=IveyCore;Trusted_Connection=True;"
    + CategoryInfo          : ObjectNotFound: (Scaffold-DbContext:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rowanmiller** [comment]
Did you install the EntityFramework.Commands package? That is the package that brings in that command. 

BTW, best to view the docs at http://docs.efproject.net/en/latest/ as they are RST. GitHub partially renders them as MarkDown... but you don't get all the content.

**Comment by aday12345** [comment]
Yes i did install the commands



Sent from my Samsung device


-------- Original message --------

**Comment by rowanmiller** [comment]
Couple more questions:
* What type of project is this in?
* Did you close and re-open Visual Studio (on occasion I have seen Package Manager Console get the wrong security policy, which prevents the commands from loading).

**Comment by aday12345** [comment]
I tried this in a class library and a console app.

Using the latest 4.x framework



Sent from my Samsung device


-------- Original message --------

**Comment by rowanmiller** [comment]
For you, are the steps to reproduce as simple as:
* File -> New -> Project...
 * Select `.NET Framework 4.6.1` from dropdown
 * Windows -> Console Application 
 * Click OK
* Tools -> NuGet Package Manager -> Package Manager Console
 * `Install-Package EntityFramework.MicrosoftSqlServer.Design -Pre` (installs 7.0.0-rc1-final)
 * `Install-Package EntityFramework.Commands -Pre` (installs 7.0.0-rc1-final)
 * `Scaffold-DbContext -provider EntityFramework.MicrosoftSqlServer -connection "Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;"`


If so, there must be something specific to your installation. A couple of initial questions to help narrow things down:
* Can you run `Get-ExecutionPolicy` in Package Manager Console and see what it returns. Sometimes when commands don't work it's because the execution policy gets set to Restricted.
* What version of VS do you have? `Help -> About Microsoft Visual Studio` - the latest version would be `14.0.24720.00 Update 1`.

Also just confirming that these are not ASP.NET 5 class libraries/console apps... since Package Manager Console commands do not work with those project types yet.

**Comment by aday12345** [comment]
I will try when i am back in the office in the new year.... thanks



Sent from my Samsung device


-------- Original message --------

**Comment by AndyFraserABZ** [comment]
I am having exactly the same problems.
I have followed the steps above except that I am creating a WinForms application.
Get-Execution returns RemoteSigned,
I am using VS 2015 version 14.0.24720.00 Update 1.

**Comment by aday12345** [comment]
Thanks for your help I am going to give this a try.

I just noticed that my PS Version is only 2.0 should I go to 3.0 for should I go to the latest and greatest.

**Comment by aday12345** [comment]
Update…

I installed PS v4 amd that looks to have fixed my issue.

But while running Scaffold-DbContext I got error ‘The given key was not present in the dictionary.’

This looks to be a known issue https://github.com/aspnet/EntityFramework/issues/3861
Do you know if there are plans for a rc2 or a work around for this issue?

**Comment by rowanmiller** [comment]
> I just noticed that my PS Version is only 2.0 should I go to 3.0 for should I go to the latest and greatest.

> I installed PS v4 and that looks to have fixed my issue.

@bricelam we do require PS 3.0 right?


@aday12345 - Regarding #3861 that is fixed and will ship in RC2 (planned for next month). In the meantime you could get out nightly builds that include the fix https://www.myget.org/Gallery/aspnetvnext

**Comment by aday12345** [comment]
Thanks for all your help

**Comment by AndyFraserABZ** [comment]
Yes, upgraded to PS4 and all seems to be fine now :-)
Many thanks.

Andy

**Comment by rowanmiller** [comment]
Great - I have https://github.com/aspnet/EntityFramework.Docs/pull/103 our for review to add this as a pre-requisite

**Comment by rowanmiller** [comment]
Thanks all for your work getting to the bottom of this one

**Comment by bricelam** [comment]
> we do require PS 3.0 right?

Yes, it's [required by our module](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/tools/EntityFramework.psd1#L23-L24). Our module should fail to load without it; I wonder if the error is getting swallowed/hidden by NuGet...

**Comment by aday12345** [comment]
do you know when we will see RC2????

**Comment by bricelam** [comment]
@aday12345 No, but when we do, it'll be posted [here](https://github.com/aspnet/Home/wiki/Roadmap#schedule).
